services:
  nginx:
    restart: always
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/service/django_static

  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/service/Dockerfile
    entrypoint: /app/docker/service/server-entrypoint.sh
    volumes:
      - static_volume:/app/service/django_static
    expose:
      - 8000
    environment:
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DB_HOST=db
      - DB_NAME=email_sender_db
      - DB_USER=bulat
      - DB_PASS=bulat54252
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bulat
      - POSTGRES_PASSWORD=bulat54252
      - POSTGRES_DB=email_sender_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - email_sender_db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "bulatvaliullin0@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "bulat54252"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:81"
    restart: unless-stopped
    networks:
      - postgres

  redis:
    restart: unless-stopped
    image: redis:7.2-alpine
    hostname: redis
    expose:
      - 6379

  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/service/Dockerfile
    entrypoint: /app/docker/service/worker-entrypoint.sh
    volumes:
      - static_volume:/app/service/django_static
    environment:
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DB_HOST=db
      - DB_NAME=email_sender_db
      - DB_USER=bulat
      - DB_PASS=bulat54252
    depends_on:
      - server
      - redis


volumes:
  email_sender_db-data:
  pgadmin-data:
  static_volume:

networks:
  postgres:
    driver: bridge
